<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Gravity Forms merge tag that generates a WooCommerce coupon on submission.
 *
 * Usage in GF confirmation or notification:
 *   {make_coupon:type:amount:expiry_days:usage_limit}
 *
 * Parameters (all optional):
 *   type        — percent | fixed_cart | fixed_product  (default: percent)
 *   amount      — numeric discount value                (default: 10)
 *   expiry_days — days until expiry; 0 = never expires  (default: 30)
 *   usage_limit — max redemptions; 0 = unlimited        (default: 1)
 *
 * Examples:
 *   {make_coupon}                       → 10% off, 30 days, single use
 *   {make_coupon:percent:15:60:1}       → 15% off, 60 days, single use
 *   {make_coupon:fixed_cart:5:0:0}      → $5 fixed, no expiry, unlimited
 *   {make_coupon:fixed_product:20:90:3} → $20 off product, 90 days, 3 uses
 *
 * The generated code is cached in GF entry meta so the same code appears
 * in both the on-screen confirmation and any notification emails.
 */
class Make_GF_Coupon {

	public function __construct() {
		add_filter( 'gform_custom_merge_tags', array( $this, 'register_merge_tag' ), 10, 4 );
		add_filter( 'gform_pre_replace_merge_tags', array( $this, 'replace_merge_tags' ), 10, 7 );
	}

	/**
	 * Add {make_coupon} to the GF merge tag picker in the form editor.
	 */
	public function register_merge_tag( $merge_tags, $form_id, $fields, $element_id ) {
		$merge_tags[] = array(
			'label' => 'Generate Coupon Code (make_coupon:type:amount:expiry_days:usage_limit)',
			'tag'   => '{make_coupon:percent:10:30:1}',
		);
		return $merge_tags;
	}

	/**
	 * Replace every {make_coupon:...} tag found in $text.
	 */
	public function replace_merge_tags( $text, $form, $entry, $url_encode, $esc_html, $nl2br, $format ) {
		if ( ! class_exists( 'WooCommerce' ) ) {
			return $text;
		}

		if ( strpos( $text, '{make_coupon' ) === false ) {
			return $text;
		}

		if ( ! $entry || empty( $entry['id'] ) ) {
			return $text;
		}

		preg_match_all( '/\{make_coupon(?::([^}]*))?\}/', $text, $matches, PREG_SET_ORDER );

		foreach ( $matches as $match ) {
			$full_tag = $match[0];
			$raw      = isset( $match[1] ) ? trim( $match[1] ) : '';
			$params   = $raw !== '' ? explode( ':', $raw ) : array();

			$type        = $this->valid_type( isset( $params[0] ) ? $params[0] : '' );
			$amount      = isset( $params[1] ) && is_numeric( $params[1] ) ? floatval( $params[1] ) : 10.0;
			$expiry_days = isset( $params[2] ) && is_numeric( $params[2] ) ? intval( $params[2] ) : 30;
			$usage_limit = isset( $params[3] ) && is_numeric( $params[3] ) ? intval( $params[3] ) : 1;

			// Key is unique per tag variant so two different {make_coupon:...} tags
			// in the same form each produce their own coupon.
			$meta_key = 'make_gf_coupon_' . md5( $full_tag );
			$code     = gform_get_meta( $entry['id'], $meta_key );

			if ( ! $code ) {
				$form_id  = isset( $form['id'] ) ? intval( $form['id'] ) : 0;
				$entry_id = intval( $entry['id'] );
				$code     = $this->create_coupon( $type, $amount, $expiry_days, $usage_limit, $form_id, $entry_id );

				if ( $code ) {
					gform_update_meta( $entry['id'], $meta_key, $code );
				}
			}

			$text = str_replace( $full_tag, $code ? $code : '', $text );
		}

		return $text;
	}

	/**
	 * Create a WooCommerce coupon and return the generated code.
	 *
	 * @return string Coupon code, or empty string on failure.
	 */
	private function create_coupon( $type, $amount, $expiry_days, $usage_limit, $form_id = 0, $entry_id = 0 ) {
		$code = $this->unique_code();
		if ( ! $code ) {
			return '';
		}

		$note      = $form_id
			? sprintf( 'Auto-generated by Gravity Forms (form #%d, entry #%d).', $form_id, $entry_id )
			: 'Auto-generated by Gravity Forms.';

		$coupon_id = wp_insert_post( array(
			'post_title'   => $code,
			'post_excerpt' => $note,
			'post_status'  => 'publish',
			'post_type'    => 'shop_coupon',
			'post_author'  => get_current_user_id() ?: 1,
		) );

		if ( is_wp_error( $coupon_id ) || ! $coupon_id ) {
			return '';
		}

		update_post_meta( $coupon_id, 'discount_type', $type );
		update_post_meta( $coupon_id, 'coupon_amount', (string) $amount );
		update_post_meta( $coupon_id, 'usage_limit', $usage_limit > 0 ? (string) $usage_limit : '' );
		update_post_meta( $coupon_id, 'usage_count', '0' );
		update_post_meta( $coupon_id, 'individual_use', 'no' );
		update_post_meta( $coupon_id, 'free_shipping', 'no' );
		update_post_meta( $coupon_id, 'exclude_sale_items', 'no' );

		if ( $expiry_days > 0 ) {
			update_post_meta( $coupon_id, 'date_expires', strtotime( '+' . $expiry_days . ' days' ) );
		}

		return $code;
	}

	/**
	 * Generate a unique MAKE-XXXXXXXX coupon code.
	 */
	private function unique_code() {
		for ( $i = 0; $i < 10; $i++ ) {
			$code = 'MAKE-' . strtoupper( wp_generate_password( 8, false ) );
			if ( ! $this->code_exists( $code ) ) {
				return $code;
			}
		}
		return '';
	}

	private function code_exists( $code ) {
		return function_exists( 'wc_get_coupon_id_by_code' )
			? (bool) wc_get_coupon_id_by_code( $code )
			: false;
	}

	/**
	 * Validate discount type, falling back to percent.
	 */
	private function valid_type( $type ) {
		$allowed = array( 'percent', 'fixed_cart', 'fixed_product' );
		return in_array( $type, $allowed, true ) ? $type : 'percent';
	}
}

new Make_GF_Coupon();
